version: '2'

volumes:
    resin-data:

services:

  mysql:
    image: mariadb
    volumes:
      - "resin-data:/data"
    ports:
      - "3306"
    privileged: true
    restart: always
    network_mode: host

  nodejs:
    build: .
    volumes:
      - "resin-data:/data"
    ports:
      - "80"
    privileged: true
    restart: always
    network_mode: host
